[package]
name = "tinyrs"
version = "0.2.0"
authors = ["Mariell Hoversholm <proximyst@proximyst.com>"]
edition = "2018"
description = "Parse Tiny format mappings in Rust."
license = "MIT"

[dependencies]
nom = "5"
serde = { version = "1", features = ["derive"] }
